// Extensio.ai — Zip Service
// Creates a .zip archive from generated extension files
// Uses archiver npm package for reliable zip creation

const archiver = require('archiver');
const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

// Helper to create a safe filename
function safeName(name) {
  return name.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();
}

async function createExtensionZip(files, extensionName) {
  if (!files || Object.keys(files).length === 0) {
    throw new Error('No files provided for zip creation');
  }

  const tmpRoot = path.join(__dirname, '../tmp');
  if (!fs.existsSync(tmpRoot)) fs.mkdirSync(tmpRoot, { recursive: true });

  const id = uuidv4();
  const dirName = `${safeName(extensionName || 'extension')}-${id}`;
  const tmpDir = path.join(tmpRoot, dirName);
  fs.mkdirSync(tmpDir, { recursive: true });

  // Ensure manifest exists and is valid JSON and contains required fields
  if (!files['manifest.json']) {
    const err = new Error('manifest.json missing from generated files');
    err.statusCode = 422;
    // cleanup created dir
    try { fs.rmdirSync(tmpDir); } catch (e) {}
    throw err;
  }

  let manifest;
  try {
    manifest = JSON.parse(files['manifest.json']);
  } catch (e) {
    const err = new Error('manifest.json is not valid JSON');
    err.statusCode = 422;
    try { fs.rmdirSync(tmpDir); } catch (e) {}
    throw err;
  }

  // Basic Manifest V3 checks
  if (manifest.manifest_version !== 3 || !manifest.name || !manifest.version) {
    const err = new Error('manifest.json is missing required fields or not manifest_version 3');
    err.statusCode = 422;
    try { fs.rmdirSync(tmpDir); } catch (e) {}
    throw err;
  }

  // Strip out missing icon references so Chrome doesn't throw a packing error
  if (manifest.icons && typeof manifest.icons === 'object') {
    for (const [size, iconPath] of Object.entries(manifest.icons)) {
      if (!files[iconPath]) {
        delete manifest.icons[size];
      }
    }
    if (Object.keys(manifest.icons).length === 0) {
      delete manifest.icons;
    }
  }

  if (manifest.action && manifest.action.default_icon) {
    const iconVal = manifest.action.default_icon;
    if (typeof iconVal === 'object' && iconVal !== null) {
      for (const [size, iconPath] of Object.entries(iconVal)) {
        if (!files[iconPath]) {
          delete iconVal[size];
        }
      }
      if (Object.keys(iconVal).length === 0) {
        delete manifest.action.default_icon;
      }
    } else if (typeof iconVal === 'string') {
      if (!files[iconVal]) {
        delete manifest.action.default_icon;
      }
    }
  }

  if (manifest.browser_action && manifest.browser_action.default_icon) {
    delete manifest.browser_action.default_icon;
  }
  if (manifest.page_action && manifest.page_action.default_icon) {
    delete manifest.page_action.default_icon;
  }

  // Update manifest.json inside files dictionary
  files['manifest.json'] = JSON.stringify(manifest, null, 2);

  // Ensure referenced files exist; if not, create small stubs where reasonable
  function ensureFile(filename, fallbackContent) {
    if (!files[filename]) {
      files[filename] = fallbackContent || `// autogenerated stub for ${filename}`;
    }
  }

  // action.default_popup -> popup.html
  if (manifest.action && manifest.action.default_popup) {
    const popup = manifest.action.default_popup;
    if (!files[popup]) {
      ensureFile(popup, `<!doctype html><meta charset="utf-8"><body><h3>${manifest.name}</h3><script></script></body>`);
    }
  }

  // background.service_worker -> background.js
  if (manifest.background && manifest.background.service_worker) {
    const bg = manifest.background.service_worker;
    if (!files[bg]) {
      ensureFile(bg, `// background service worker for ${manifest.name}`);
    }
  }

  // content_scripts[*].js -> ensure those files exist
  if (Array.isArray(manifest.content_scripts)) {
    for (const cs of manifest.content_scripts) {
      if (Array.isArray(cs.js)) {
        cs.js = cs.js.filter((jsFile) => {
          if (!files[jsFile]) {
            // create a small stub and keep it
            ensureFile(jsFile, `// content script ${jsFile} for ${manifest.name}`);
          }
          return true;
        });
      }
    }
  }

  // Write all files into the uniquely-named tmp directory preserving subdirectories safely
  for (const [filename, content] of Object.entries(files)) {
    if (typeof content === 'undefined') continue;

    // Split filename by / or \ to handle subdirectories safely
    const parts = filename.split(/[/\\]/);
    
    // Sanitize each directory/file name component to prevent traversal
    const safeParts = parts
      .map(part => part.replace(/[^a-zA-Z0-9._-]/g, ''))
      .filter(part => part !== '' && part !== '.' && part !== '..');
      
    if (safeParts.length === 0) continue;
    
    // Resolve full target path
    const targetFilePath = path.join(tmpDir, ...safeParts);
    
    // Ensure the parent directory exists
    const parentDir = path.dirname(targetFilePath);
    if (!fs.existsSync(parentDir)) {
      fs.mkdirSync(parentDir, { recursive: true });
    }
    
    fs.writeFileSync(targetFilePath, content, 'utf8');
  }

  const zipPath = `${tmpDir}.zip`;

  await new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => resolve());
    output.on('error', reject);
    archive.on('warning', (err) => {
      if (err.code === 'ENOENT') console.warn('Archiver warning', err);
      else reject(err);
    });
    archive.on('error', reject);

    archive.pipe(output);
    // Add files from tmpDir into the root of the zip
    archive.directory(tmpDir, false);
    archive.finalize();
  });

  // Remove the working folder, keep zip for download
  try {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  } catch (e) {
    console.warn('Failed to remove tmpDir', tmpDir, e.message);
  }

  return zipPath;
}

function cleanupZip(zipPath) {
  if (fs.existsSync(zipPath)) {
    fs.unlinkSync(zipPath);
  }
}

module.exports = { createExtensionZip, cleanupZip };