package com.extgen.platform.service;

import com.extgen.platform.model.GenerateRequest;
import com.extgen.platform.model.GenerateResponse;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.*;

@Service
public class ExtensionGeneratorService {

    // In-memory store (replace with a database in production)
    private final Map<String, GenerateResponse> store = new LinkedHashMap<>();

    /**
     * Generate a browser extension from a text prompt.
     * In production, this would call an AI service (e.g. OpenAI API).
     */
    public GenerateResponse generate(GenerateRequest request) {
        String id = UUID.randomUUID().toString();
        String name = extractName(request.getPrompt());

        GenerateResponse response = new GenerateResponse();
        response.setId(id);
        response.setName(name);
        response.setDescription(request.getPrompt());
        response.setBrowser(request.getBrowser());
        response.setCategory(request.getCategory());
        response.setStatus("Draft");
        response.setCreatedAt(LocalDateTime.now());
        response.setFiles(buildFiles(name, request));

        store.put(id, response);
        return response;
    }

    public List<GenerateResponse> getAll() {
        return new ArrayList<>(store.values());
    }

    public Optional<GenerateResponse> getById(String id) {
        return Optional.ofNullable(store.get(id));
    }

    public void delete(String id) {
        store.remove(id);
    }

    // ---- Private Helpers ----

    private String extractName(String prompt) {
        // Simple heuristic: take first 4 words, capitalize
        String[] words = prompt.trim().split("\\s+");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < Math.min(3, words.length); i++) {
            sb.append(capitalize(words[i]));
        }
        return sb.toString() + " Extension";
    }

    private String capitalize(String word) {
        if (word == null || word.isEmpty()) return word;
        return Character.toUpperCase(word.charAt(0)) + word.substring(1).toLowerCase();
    }

    private Map<String, String> buildFiles(String name, GenerateRequest req) {
        Map<String, String> files = new LinkedHashMap<>();

        files.put("manifest.json", buildManifest(name, req.getBrowser()));
        files.put("popup.html", buildPopupHtml(name));
        files.put("popup.js", buildPopupJs());
        files.put("content.js", buildContentJs());
        files.put("background.js", buildBackgroundJs());

        return files;
    }

    private String buildManifest(String name, String browser) {
        int mv = browser.equals("Firefox") ? 2 : 3;
        return "{\n"
            + "  \"manifest_version\": " + mv + ",\n"
            + "  \"name\": \"" + name + "\",\n"
            + "  \"version\": \"1.0.0\",\n"
            + "  \"description\": \"Generated by ExtGen.dev\",\n"
            + "  \"permissions\": [\"activeTab\", \"storage\"],\n"
            + "  \"action\": {\n"
            + "    \"default_popup\": \"popup.html\"\n"
            + "  },\n"
            + "  \"content_scripts\": [{\n"
            + "    \"matches\": [\"<all_urls>\"],\n"
            + "    \"js\": [\"content.js\"]\n"
            + "  }],\n"
            + "  \"background\": {\n"
            + "    \"service_worker\": \"background.js\"\n"
            + "  }\n"
            + "}";
    }

    private String buildPopupHtml(String name) {
        return "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
            + "  <meta charset=\"UTF-8\">\n"
            + "  <title>" + name + "</title>\n"
            + "  <style>\n"
            + "    body { font-family: sans-serif; width: 300px; padding: 16px; }\n"
            + "    h2 { color: #00e5ff; font-size: 1rem; }\n"
            + "    button { background: #7c3aed; color: white; border: none;\n"
            + "             padding: 8px 16px; border-radius: 6px; cursor: pointer; }\n"
            + "  </style>\n</head>\n<body>\n"
            + "  <h2>" + name + "</h2>\n"
            + "  <p id=\"status\">Ready</p>\n"
            + "  <button id=\"actionBtn\">Activate</button>\n"
            + "  <script src=\"popup.js\"></script>\n"
            + "</body>\n</html>";
    }

    private String buildPopupJs() {
        return "document.getElementById('actionBtn').addEventListener('click', () => {\n"
            + "  chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {\n"
            + "    chrome.tabs.sendMessage(tabs[0].id, { type: 'ACTIVATE' });\n"
            + "    document.getElementById('status').textContent = 'Activated!';\n"
            + "  });\n"
            + "});";
    }

    private String buildContentJs() {
        return "chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {\n"
            + "  if (msg.type === 'ACTIVATE') {\n"
            + "    console.log('Extension activated on:', window.location.href);\n"
            + "    // TODO: Add your extension logic here\n"
            + "    sendResponse({ success: true });\n"
            + "  }\n"
            + "});";
    }

    private String buildBackgroundJs() {
        return "chrome.runtime.onInstalled.addListener(() => {\n"
            + "  console.log('Extension installed successfully.');\n"
            + "  chrome.storage.sync.set({ enabled: false });\n"
            + "});";
    }
}
